name: Sync Hermes Image to Aliyun

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Pull Original Image
      run: |
        docker pull nousresearch/hermes-agent:latest

    - name: 2. Login to Aliyun
      run: |
        echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login --username="wwplay@gmail.com" --password-stdin crpi-g8pfju6vtmetiw0d.cn-shanghai.personal.cr.aliyuncs.com

    - name: 3. Retag and Push to Aliyun
      run: |
        docker tag nousresearch/hermes-agent:latest ://aliyuncs.com
        docker push ://aliyuncs.com
