name: Export Open WebUI Tar

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Pull Image via GitHub Network
      run: |
        # 使用微软海外 Azure 骨干网瞬间无限制拉取最新正版镜像
        docker pull ghcr.io/open-webui/open-webui:main

    - name: 2. Save Image to Local File
      run: |
        # 把几百兆的镜像打包压缩成一个纯粹的离线包文件
        docker save ghcr.io/open-webui/open-webui:main -o open-webui.tar

    - name: 3. Upload File to Wetransfer (No Passwords Needed)
      run: |
        # 利用全球免密秒传工具，将这个离线包直接上传到国内完全可连的云端加速网关
        curl -sL https://git.io | sh
        ./transfer wet open-webui.tar
